version: '3'
services:
  vpronginx:
    image: vevadevops/vpronginx
    ports:
      - "80:80"

  vproapp:
    image: vevadevops/vproappfix
    ports:
      - "8080:8080"

  vprodb:
    image: vevadevops/vprdbfix
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

volumes:
  vprodbdata: {}
